[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
student_intro = "BxeevkN4k43FjHgx1z3Edw4NNcQoUML7gNJX68WLqaCn"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
